# -*- coding: utf-8 -*-
"""NEC1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PT31Kip0K1W_8QXleGWX6iLN7rCnnJNT
"""



"""## **First Program in PyTorch**"""

import torch
import numpy as np
import sys
import matplotlib as plt

print(f'python vesion: {sys.version}')
print(f'Numpy version: {np.version.version}')
print(f'PyTorch version: {torch.version.__version__}')
print("Torch Version", torch.__version__)
print(f'Matplotlib version: {plt.__version__}')
print(f'GPU present: {torch.cuda.is_available()}')

